### ISSUE TITLE
Add tests and continuous deployments on heroku

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_walls#1]
What tests can we add to this?
* Codecove
* Codeclimate
* Codacy
* Travis
* https://houndci.com/configuration (.hound.yml)
* http://eslint.org/docs/user-guide/configuring (.eslintrc)

**Comment by mariobehling** [comment]
@sudheesh001 Could you please help to get this project on its feet and help to set up testing and automatic heroku deployments?

**Comment by mariobehling** [comment]
Please also set up a branch "development" and deploy from development to Heroku. Once a week please merge to Master.

**Comment by mariobehling** [comment]
Please give me the link to the Heroku deployment.

**Comment by sudheesh001** [comment]
@leonmak Is the exact problem that you're facing here with respect to the settings task which is failing ? i.e. the custom_configFile.json isn't getting generated, What you'd need to do here is to set these as ENV variables instead and modify the code to use the value from JSON or the ENV value. https://www.npmjs.com/package/dotenv could be helpful.

**Comment by mariobehling** [comment]
@sudheesh001 Please help to do it.

**Comment by leonmak** [comment]
@sudheesh001 I'm not familiar with the steps to deploy to heroku, I can push to it but it just keeps giving error

**Comment by leonmak** [comment]
@mariobehling sorry for the delays, finally managed to set it up at tranquil-river-53177.herokuapp.com

**Comment by mariobehling** [comment]
@leonmak Took a minute to load. Will check it out. Thanks!

Could you please change the URL to loklak_wall.herokuapp.com?

**Comment by leonmak** [comment]
@mariobehling ok it is https://loklak-wall.herokuapp.com/ , underscores not allowed

**Comment by mariobehling** [comment]
Thanks! Good job!
